version: '3'
services:
  hub:
    image: selenium/hub
    ports:
      - 4444:4444
      - 4442:4442
      - 4443:4443
  chrome:
    image: selenium/standalone-chrome
    shm_size: '2g'
    depends_on:
    - hub
    environment:
    - SE_EVENT_BUS_HOST=hub
    - SE_EVENT_BUS_PUBLISH_PORT=4442
    - SE_EVENT_BUS_SUBSCRIBE_PORT=4442

  firefox:
    image: selenium/node-firefox
    shm_size: '2g'
    depends_on:
    - hub
    environment:
    - SE_EVENT_BUS_HOST=hub
    - SE_EVENT_BUS_PUBLISH_PORT=4442
    - SE_EVENT_BUS_SUBSCRIBE_PORT=4442